<?php

declare(strict_types=1);

namespace App\Tests\Integration;

use App\Feature\Token\Command\IssueToken\IssueTokenCommand;
use App\Feature\Token\Command\IssueToken\IssueTokenHandler;
use App\Feature\Token\MongoTokenRepository;
use App\Feature\Token\TokenAuthenticator;
use PhpSoftBox\Api\Description\ApiDescription;
use PhpSoftBox\Auth\Token\CredentialCodec;
use PhpSoftBox\Clock\SystemClock;
use PhpSoftBox\MongoDb\Configurator\MongoFactory;
use PhpSoftBox\MongoDb\Connection\MongoConnectionManager;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\CoversMethod;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

use function bin2hex;
use function getenv;
use function random_bytes;

#[CoversClass(MongoTokenRepository::class)]
#[CoversMethod(MongoTokenRepository::class, 'insert')]
#[CoversMethod(MongoTokenRepository::class, 'find')]
final class MongoTokenTest extends TestCase
{
    /** A new Mongo connection reads the persisted credential without exposing its secret.
     * @see MongoTokenRepository::insert()
     * @see MongoTokenRepository::find()
     */
    #[Test]
    public function credentialSurvivesConnectionRecreation(): void
    {
        $uri = getenv('OZON_TEST_MONGO_URI');
        if ($uri === false || $uri === '') {
            self::markTestSkipped('Set OZON_TEST_MONGO_URI to run the isolated MongoDB contract test.');
        }
        $config = ['uri' => $uri, 'database' => 'ozon_test_' . bin2hex(random_bytes(8))];
        $mongo  = new MongoConnectionManager(new MongoFactory($config));
        try {
            $codec = new CredentialCodec();
            $api   = ApiDescription::create('ozon-seller')->build();
            $clock = new SystemClock();

            $issued = new IssueTokenHandler(new MongoTokenRepository($mongo), $codec, $api, $clock)
                            ->handle(new IssueTokenCommand('1001'));
            $anotherConnection = new MongoConnectionManager(new MongoFactory($config));

            $auth = new TokenAuthenticator(new MongoTokenRepository($anotherConnection), $codec, $api, $clock);

            self::assertSame('1001', $auth->authenticate('1001', $issued->apiKey)?->clientId);
            self::assertNull($auth->authenticate('2002', $issued->apiKey));
            $document = $anotherConnection->collection('api_tokens')->findOne([]);
            self::assertNotNull($document);
            self::assertArrayNotHasKey('api_key', (array) $document);
            self::assertNotSame($issued->apiKey, $document['secret_hash']);
        } finally {
            // The name is generated by this test; no application database is ever reset.
            $mongo->database()->drop();
        }
    }
}
